.TH fenris-bug 1
.SH NAME
fenris-bug \- bug-reporting utility for fenris
.SH SYNOPSIS
.B fenris-bug
.br
.SH "DESCRIPTION"
This is a bug reporting tool for
.BR fenris (1).
It allows you to prepare and send a bugreport interactively,
and to provide most accurate information.

.SH SEE ALSO
.BR fenris (1),
.BR aegir (1),
.BR nc-aegir (1),
.BR ragnarok (1),
.BR dress (1),
.BR fprints (1),
.BR getfprints (1),
.BR ragsplit (1),
.BR strace (1),
.BR ltrace (1),
.BR gdb (1),
.BR objdump (1),
.BR ptrace (2),
.BR fnprints.dat (5).

.SH AUTHOR
.B fenris-bug
was written by Michal Zalewski <lcamtuf@coredump.cx>.
