.TH fnprints.dat 5
.SH NAME
fnprints.dat \- fenris function fingerprints database
.SH "DESCRIPTION"
This file is used by
.BR fenris (1)
utility to recognize library functions embedded inside
static binaries. Please refer to
.BR /usr/doc/fenris/README
or
.BR http://lcamtuf.coredump.cx/fenris/
for more information on this program, the format of this file,
etc.

.SH SEE ALSO
.BR fenris (1),
.BR aegir (1),
.BR nc-aegir (1),
.BR fenris-bug (1),
.BR dress (1),
.BR ragnarok (1),
.BR getfprints (1),
.BR fprints (1),
.BR ragsplit (1),
.BR strace (1),
.BR ltrace (1),
.BR gdb (1),
.BR objdump (1),
.BR ptrace (2),
