.TH nc-aegir 1
.SH NAME
nc-aegir \- interactive GUI debugger frontend for Fenris
.SH SYNOPSIS
.B nc-aegir
.br
.SH "DESCRIPTION"
nc-aegir is a variation of 
.BR aegir (1) ,
an interactive debugging frontend for 
.BR fenris (1) ,
a program execution path analysis tool. It has
SoftICE-alike look and feel, and provides an extensive easy to use GUI,
but other than that, incorporates all the
functionality of Aegir. An interactive help is available (Alt-H). Please
see 
.BR aegir (1)
manpage for more information.

.SH SEE ALSO
.BR aegir (1),
.BR dress (1),
.BR fenris (1),
.BR ragnarok (1),
.BR fprints (1),
.BR getfprints (1),
.BR fenris-bug (1),
.BR ragsplit (1),
.BR strace (1),
.BR ltrace (1),
.BR gdb (1),
.BR objdump (1),
.BR ptrace (2),
.BR fnprints.dat (5).

.SH AUTHOR
.B nc-aegir
was written by Andrzej Szombierski <qq@kuku.eu.org>.

